milestone/nogoods
ellmau/adf-obdd pull request #74
Opened 2022-06-15 15:41 UTC by ellmau

# What does this PR do?

* Resolves #73 
* Closes #64 

Implementation of an alternative NoGoodStore to easier learn and imply conclusions.

# Checklist before creating a non-draft PR

- [ ] All tests are passing
- [ ] Clippy has no complains
- [ ] Code is `rustfmt` formatted
- [ ] Applicable labels are chosen (Note: it is not necessary to replicate the labels from the related issues)
- [ ] There are no other open [Pull Requests](https://github.com/ellmau/adf-obdd/pulls) for the same update/change.
  - [ ] If there is a good reason to have another PR for the same update/change, it is well justified.

# Checklist on Guidelines and Conventions

- [ ] Commit messages follow our guidelines
- [ ] Code is self-reviewed
- [ ] Naming conventions are met
- [ ] New features are tested
  - [ ] `quickcheck` has been considered
  - [ ] All variants are considered and checked
- Clippy Compiler-exceptions
  - [ ] Used in a sparse manner
  - [ ] If used, a separate comment describes and justifies its use
- [ ] `rustdoc` comments are self-reviewed and descriptive
- Error handling
  - [ ] Use of `panic!(...)` applications is justified on non-recoverable situations
  - [ ] `expect(...)` is used over `unwrap()` (except obvious test-cases)
- [ ] No unsafe code (exceptions need to be discussed specifically)

2022-06-21 16:00 UTC, mmarx commented on lib/src/nogoods.rs
> +	    let idx:u32 = idx.try_into().expect("no-good learner implementation is based on the assumption that only u32::MAX-many variables are in place");
Break the string literal to work around rust-lang/rustfmt#3863, which prevents formatting of the remainder of the function.

```suggestion
                let idx: u32 = idx.try_into().expect(
                    "no-good learner implementation is based on the assumption \
                     that only u32::MAX-many variables are in place",
                );
```

2022-06-21 22:16 UTC, ellmau reviewed
LGTM - Nice refactor to avoid the box and allow a functionpointer to be responsible as the heuristics functions.

2022-06-22 15:46 UTC, ellmau commented
### Next step:
the consistency of choices and learnt information should be verified with respect to the adf more often to avoid local hill optimisation effects

2022-08-01 17:02 UTC, mmarx requested changes
lmgtm, I just have a few remarx.

2022-08-02 08:06 UTC, ellmau commented on lib/src/nogoods.rs
> +// TODO:make struct crate-private
Yes it is no longer a goal for this PR and so the comment got removed

2022-08-02 08:07 UTC, ellmau commented on lib/src/nogoods.rs
> +    pub fn is_violating(&self, other: &NoGood) -> bool {
Fixed by b3b2632.

2022-08-02 08:17 UTC, ellmau commented on lib/src/nogoods.rs
> +        }
Thanks for the hint - flake got bumped just now (fac10dd) and therefore 1.62 is the current edition.

2022-08-02 11:55 UTC, mmarx approved these changes

2022-08-02 12:02 UTC, merged